[project]
name = "netmob25-embedding"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.13"
dependencies = [
    "folium>=0.20.0",
    "geopandas>=1.1.1",
    "h3>=4.3.1",
    "infostop>=0.1.9",
    "ipykernel>=6.30.1",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.5",
    "pacmap>=0.8.0",
    "plotly>=6.3.0",
    "rapidfuzz>=3.13.0",
    "seaborn>=0.13.2",
    "tqdm>=4.67.1",
    "umap-learn==0.5.5",
    "unidecode>=1.4.0",
    "numpy==1.26.4",
    "scipy==1.11.4",
    "gensim==4.3.3",
    "numba"
]

[tool.setuptools]
packages = ['src'] # uv pip install -e .
